### ISSUE TITLE
 Change of QRCode routing

### ISSUE THREAD

**Issue by DidoNael** [k01ek/netbox-qrcode#10]
Hello friends, which parameter is it necessary to change so that the QRCode forwards us to the server's ip and not localhost?

**Comment by k01ek** [comment]
Hi @DidoNael ! QRCode uses a built-in Django tool for getting full path URL for an object. As far as I know, Django gets host from one of these request headers: 
* HTTP_X_FORWARDED_HOST
* HTTP_HOST
* SERVER_NAME
So, you can do that in different ways. If you don't use web servers like Nginx or Apache as a proxy, you can set IP right in the request. Just open http://127.0.0.1 instead of http://localhost. Otherwise, you can set HTTP_X_FORWARDED_HOST or SERVER_NAME in the web server configuration.
